/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SubItem = {
  _type: 'subItem'
  icon?: 'bud' | 'acorn'
  title?: string
  text?: string
}

export type ServicesTile = {
  _type: 'servicesTile'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: string
  text?: string
  link?: LinkDefined
}

export type ContactSection = {
  _type: 'contactSection'
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'h5'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  formTerms?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<
      | {
          reference?:
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'post'
              }
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
          _type: 'internalLink'
          _key: string
        }
      | {
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | {
          reference?:
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'post'
              }
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
          _type: 'internalLink'
          _key: string
        }
      | {
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  topPadding?: boolean
}

export type BenifitsSection = {
  _type: 'benifitsSection'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  icon?: 'bud' | 'acorn'
  subtitle?: string
  title?: string
  text?: string
  subItem?: Array<
    {
      _key: string
    } & SubItem
  >
  links?: Array<
    {
      _key: string
    } & LinkDefined
  >
  mirror?: boolean
  topPadding?: boolean
  highlighted?: boolean
}

export type LocationSection = {
  _type: 'locationSection'
  subtitle?: string
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2' | 'h3'
    listItem?: never
    markDefs?: Array<
      {
        _key: string
      } & TextColor
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'h5' | 'body2' | 'blockquote'
    listItem?: never
    markDefs?: Array<
      {
        _key: string
      } & TextColor
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  topPadding?: boolean
  textAlign?: 'flex-start' | 'center'
}

export type ImageCarouselSection = {
  _type: 'imageCarouselSection'
  topPadding?: boolean
  images?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
}

export type TestimonialSection = {
  _type: 'testimonialSection'
  topPadding?: boolean
  backgroundColor?: SimplerColor
  testimonialTiles?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'quote'
  }>
}

export type HeaderSectionAccommodationSearch = {
  _type: 'headerSectionAccommodationSearch'
  title?: string
  text?: string
  searchColour?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'designSystemColor'
  }
  showSearch?: boolean
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Categories = {
  _id: string
  _type: 'categories'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  locale?: 'en-US' | 'en-GB' | 'fr-FR'
  title?: string
  name?: string
  slug?: Slug
  pageBuilder?: Array<
    | ({
        _key: string
      } & EmbedSection)
    | ({
        _key: string
      } & TitleSection)
    | ({
        _key: string
      } & TextSection)
    | ({
        _key: string
      } & FeatureSection)
    | ({
        _key: string
      } & BorderSection)
    | ({
        _key: string
      } & HotspotSection)
    | ({
        _key: string
      } & HeaderSection)
    | ({
        _key: string
      } & TestimonialSection)
    | ({
        _key: string
      } & TeamSection)
    | ({
        _key: string
      } & RecipesSection)
    | ({
        _key: string
      } & VideoSection)
    | ({
        _key: string
      } & FeaturesListSection)
    | ({
        _key: string
      } & CtaSection)
    | ({
        _key: string
      } & NewsletterSection)
    | ({
        _key: string
      } & ImageCarouselSection)
    | ({
        _key: string
      } & BlogSection)
    | ({
        _key: string
      } & StepsSection)
    | ({
        _key: string
      } & TimelineSection)
    | ({
        _key: string
      } & LocationSection)
    | ({
        _key: string
      } & ContactSection)
    | ({
        _key: string
      } & ClientLoginSection)
  >
}

export type Link = {
  _type: 'link'
  external?: string
  internal?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'post'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
}

export type NavigationItem = {
  _type: 'navigationItem'
  link?: LinkDefined
  childItems?: Array<
    {
      _key: string
    } & LinkDefined
  >
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  navId?: Slug
  items?: Array<
    {
      _key: string
    } & NavigationItem
  >
}

export type ColorChoice = {
  _type: 'colorChoice'
  oneOffColor?: Color
  designSystemColor?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'designSystemColor'
  }
}

export type Overlay = '0.1' | '0.2' | '0.3' | '0.4' | '0.5'

export type TextAlign = 'left' | 'center'

export type Icons = 'bud' | 'acorn'

export type ClientLoginSection = {
  _type: 'clientLoginSection'
  subtitle?: string
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2' | 'h3'
    listItem?: never
    markDefs?: Array<
      {
        _key: string
      } & TextColor
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'caption' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | {
          reference?:
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'post'
              }
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
          _type: 'internalLink'
          _key: string
        }
      | {
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }
      | {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
          }
          _type: 'file'
          _key: string
        }
      | ({
          _key: string
        } & TextColor)
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  topPadding?: boolean
  loginTile?: Array<
    {
      _key: string
    } & LoginTile
  >
}

export type LoginTile = {
  _type: 'loginTile'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  link?: LinkDefined
}

export type TimeTile = {
  _type: 'timeTile'
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type TimelineSection = {
  _type: 'timelineSection'
  topPadding?: boolean
  subtitle?: string
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h2' | 'h3' | 'h4' | 'h5'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  leftText?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  rightText?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  timelineColor?: SimplerColor
  steps?: Array<
    {
      _key: string
    } & TimeTile
  >
}

export type StepDivider = {
  _type: 'stepDivider'
  subtitle?: string
  title?: string
}

export type StepTile = {
  _type: 'stepTile'
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  secondTitle?: string
  involves?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  tileOrientation?: boolean
}

export type StepsSection = {
  _type: 'stepsSection'
  topPadding?: boolean
  subtitle?: string
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h2' | 'h3' | 'h4' | 'h5'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  textAlign?: 'flex-start' | 'center'
  tileColor?: SimplerColor
  steps?: Array<
    | ({
        _key: string
      } & StepTile)
    | ({
        _key: string
      } & StepDivider)
    | ({
        _key: string
      } & AccordionTile)
  >
}

export type TestimonialTile = {
  _type: 'testimonialTile'
  quote?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  citeName?: string
  citeLocation?: string
}

export type BlogSection = {
  _type: 'blogSection'
  subtitle?: string
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  leftText?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  rightText?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  showArchive?: ShowArchive
  topPadding?: boolean
}

export type ShowArchive = {
  _type: 'showArchive'
  setArchive?: boolean
  archive?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'categories'
  }>
}

export type FeaturesTile = {
  _type: 'featuresTile'
  title?: string
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h4' | 'h5'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      {
        _key: string
      } & TextColor
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  link?: LinkDefined
}

export type CtaSection = {
  _type: 'ctaSection'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: string
  text?: string
  links?: Array<
    {
      _key: string
    } & LinkDefined
  >
  leftAlign?: TextAlign
  topPadding?: boolean
  overlay?: Overlay
}

export type FeaturesListSection = {
  _type: 'featuresListSection'
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2' | 'h3'
    listItem?: never
    markDefs?: Array<
      {
        _key: string
      } & TextColor
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'h5' | 'body2' | 'blockquote'
    listItem?: never
    markDefs?: Array<
      {
        _key: string
      } & TextColor
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  topPadding?: boolean
  featuresTile?: Array<
    {
      _key: string
    } & FeaturesTile
  >
}

export type VideoSection = {
  _type: 'videoSection'
  topPadding?: boolean
  video?: VideoId
}

export type VideoId = {
  _type: 'videoId'
  url?: string
  id?: string
  service?: string
  thumbnail?: string
}

export type NewsletterSection = {
  _type: 'newsletterSection'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'h5' | 'body2' | 'blockquote'
    listItem?: never
    markDefs?: Array<
      {
        _key: string
      } & TextColor
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3' | 'h4' | 'h5' | 'body2' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  topPadding?: boolean
  mirror?: boolean
  backgroundColor?: SimplerColor
}

export type RecipesSection = {
  _type: 'recipesSection'
  backgroundColour?: SimplerColor
  showRecipesArchive?: ShowRecipesArchive
  verticalSpace?: VerticalSpace
}

export type TeamSection = {
  _type: 'teamSection'
  topPadding?: boolean
  subtitle?: string
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  leftText?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  rightText?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3' | 'h4' | 'h5' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  links?: Array<
    {
      _key: string
    } & LinkDefined
  >
  tileColor?: SimplerColor
  teamTiles?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'teamMember'
  }>
}

export type HeaderSection = {
  _type: 'headerSection'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: string
  alignment?: TextAlign
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2'
    listItem?: never
    markDefs?: Array<
      {
        _key: string
      } & TextColor
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  links?: Array<
    {
      _key: string
    } & LinkDefined
  >
  backgroundColour?: SimplerColor
  verticalSpace?: VerticalSpace
}

export type HotspotSection = {
  _type: 'hotspotSection'
  title?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  hotspots?: Array<
    {
      _key: string
    } & HotspotItem
  >
}

export type BorderSection = {
  _type: 'borderSection'
  borderType?: 'Type 2' | 'Type 3' | 'Type 6'
  borderDirection?: 'Top' | 'Bottom'
  mirror?: boolean
  joiningColour?: SimplerColor
  backgroundColour?: SimplerColor
}

export type TextSection = {
  _type: 'textSection'
  text?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & TextColumns)
          | {
              reference?:
                | {
                    _ref: string
                    _type: 'reference'
                    _weak?: boolean
                    [internalGroqTypeReferenceTo]?: 'post'
                  }
                | {
                    _ref: string
                    _type: 'reference'
                    _weak?: boolean
                    [internalGroqTypeReferenceTo]?: 'page'
                  }
                | {
                    _ref: string
                    _type: 'reference'
                    _weak?: boolean
                    [internalGroqTypeReferenceTo]?: 'recipes'
                  }
              _type: 'internalLink'
              _key: string
            }
          | {
              href?: string
              blank?: boolean
              _type: 'link'
              _key: string
            }
          | {
              asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
              }
              _type: 'file'
              _key: string
            }
          | ({
              _key: string
            } & TextColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  backgroundColour?: SimplerColor
  link?: LinkDefined
  verticalSpace?: VerticalSpace
  sideAssets?: SupportingAssets
}

export type TitleSection = {
  _type: 'titleSection'
  title?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5'
    listItem?: never
    markDefs?: Array<
      {
        _key: string
      } & TextColor
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  backgroundColour?: SimplerColor
  link?: LinkDefined
  verticalSpace?: VerticalSpace
  alignment?: TextAlign
  sideAssets?: SupportingAssets
}

export type LinkDefined = {
  _type: 'linkDefined'
  text?: string
  link?: Link
}

export type EmbedSection = {
  _type: 'embedSection'
  scriptTag?: string
  embedCode?: Code
  backgroundColour?: SimplerColor
  verticalSpace?: VerticalSpace
  containerWidth?: ContainerWidth
}

export type FeatureSection = {
  _type: 'featureSection'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'overline'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | ({
          _key: string
        } & TextColor)
      | ({
          _key: string
        } & TextColumns)
      | {
          reference?:
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'post'
              }
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'recipes'
              }
          _type: 'internalLink'
          _key: string
        }
      | {
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }
      | {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
          }
          _type: 'file'
          _key: string
        }
      | ({
          _key: string
        } & TextColor)
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  links?: Array<
    {
      _key: string
    } & LinkDefined
  >
  mirror?: boolean
  backgroundColour?: SimplerColor
  centerAsset?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  verticalSpace?: VerticalSpace
}

export type Quote = {
  _id: string
  _type: 'quote'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  quoteText?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  cite?: Cite
}

export type HotspotItem = {
  _type: 'hotspotItem'
  details?: string
  x?: number
  y?: number
}

export type AccordionTile = {
  _type: 'accordionTile'
  title?: string
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2' | 'h3' | 'h4'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | {
          reference?:
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'post'
              }
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
          _type: 'internalLink'
          _key: string
        }
      | {
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }
      | {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
          }
          _type: 'file'
          _key: string
        }
    >
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type ShowRecipesArchive = {
  _type: 'showRecipesArchive'
  setArchive?: boolean
  archive?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'recipes'
  }>
}

export type Cite = {
  _type: 'cite'
  teamMemberCite?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'teamMember'
  }
  externalCite?: ExternalCite
}

export type ExternalCite = {
  _type: 'externalCite'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  citeName?: string
  citeLocation?: string
}

export type TeamMember = {
  _id: string
  _type: 'teamMember'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  locale?: 'en-US' | 'en-GB' | 'fr-FR'
  title?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  tileImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  name?: string
  slug?: Slug
  navColor?: SimplerColor
  navOverlay?: boolean
  position?: string
  email?: string
  linkedIn?: string
  excerpt?: string
  bio?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3' | 'h4' | 'h5' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              reference?:
                | {
                    _ref: string
                    _type: 'reference'
                    _weak?: boolean
                    [internalGroqTypeReferenceTo]?: 'post'
                  }
                | {
                    _ref: string
                    _type: 'reference'
                    _weak?: boolean
                    [internalGroqTypeReferenceTo]?: 'page'
                  }
              _type: 'internalLink'
              _key: string
            }
          | {
              href?: string
              blank?: boolean
              _type: 'link'
              _key: string
            }
          | {
              asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
              }
              _type: 'file'
              _key: string
            }
          | ({
              _key: string
            } & TextColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  pageBuilder?: Array<
    | ({
        _key: string
      } & HeaderSection)
    | ({
        _key: string
      } & TestimonialSection)
    | ({
        _key: string
      } & TeamSection)
    | ({
        _key: string
      } & RecipesSection)
    | ({
        _key: string
      } & VideoSection)
    | ({
        _key: string
      } & FeaturesListSection)
    | ({
        _key: string
      } & CtaSection)
    | ({
        _key: string
      } & NewsletterSection)
    | ({
        _key: string
      } & ImageCarouselSection)
    | ({
        _key: string
      } & BlogSection)
    | ({
        _key: string
      } & StepsSection)
    | ({
        _key: string
      } & TimelineSection)
    | ({
        _key: string
      } & LocationSection)
    | ({
        _key: string
      } & ContactSection)
    | ({
        _key: string
      } & ClientLoginSection)
  >
}

export type TextColumns = {
  _type: 'textColumns'
  columns?: '1' | '2' | '3' | '4'
}

export type SupportingAssets = {
  _type: 'supportingAssets'
  leftAsset?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  rightAsset?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Hotspots = {
  _id: string
  _type: 'hotspots'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  featureImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  hotspots?: Array<
    {
      _key: string
    } & HotspotItem
  >
}

export type ContainerWidth = {
  _type: 'containerWidth'
  width?: 'sm' | 'md' | 'lg'
}

export type VerticalSpace = {
  _type: 'verticalSpace'
  topPadding?: 'MS-6' | 'MS6'
  bottomPadding?: 'MS-6' | 'MS6'
}

export type IngredientItem = {
  _type: 'ingredientItem'
  ingredient?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'ingredients'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'recipes'
      }
  wholeNumber?: number
  fraction?: '1/2' | '1/3' | '1/4' | '3/4' | '2/3'
  unit?: 'grams' | 'cup' | 'Tbsp.' | 'tsp.' | 'bunch' | 'handful' | 'pinch' | 'glug'
  preparation?:
    | 'Roughly Chopped'
    | 'Chopped'
    | 'Finely Chopped'
    | 'Finely Chopped or Sliced'
    | 'Sliced'
    | 'Shredded'
    | 'Grated'
    | 'Crushed'
    | 'Drained & Rinsed'
    | 'Drained & Finely Chopped'
    | 'Juice of'
    | 'to taste'
  optional?: boolean
}

export type Ingredients = {
  _id: string
  _type: 'ingredients'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  date?: string
  alergy?: boolean
  foodGroup?: Array<string>
}

export type IngredientsList = Array<
  {
    _key: string
  } & IngredientItem
>

export type ImageOptions = {
  _type: 'imageOptions'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  mixBlendMode?: 'multiply' | 'hard-light'
}

export type DesignSystemColor = {
  _id: string
  _type: 'designSystemColor'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  color?: Color
}

export type NewsletterSetup = {
  _type: 'newsletterSetup'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: string
  text?: string
  consentText?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type CompanyDetails = Array<
  {
    _key: string
  } & CompanyDetailType
>

export type CompanyDetailType = {
  _type: 'companyDetailType'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: string
  address1?: string
  address2?: string
  address3?: string
  address4?: string
  county?: string
  postcode?: string
  phone?: string
  email?: string
  geopoint?: Geopoint
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  companyDetails?: CompanyDetails
  footerDetails?: FooterDetails
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  locale?: 'en-US' | 'en-GB' | 'fr-FR'
  title?: string
  slug?: Slug
  date?: string
  modified?: string
  status?:
    | 'publish'
    | 'future'
    | 'draft'
    | 'pending'
    | 'private'
    | 'trash'
    | 'auto-draft'
    | 'inherit'
  pageBuilder?: Array<
    | ({
        _key: string
      } & EmbedSection)
    | ({
        _key: string
      } & TitleSection)
    | ({
        _key: string
      } & TextSection)
    | ({
        _key: string
      } & FeatureSection)
    | ({
        _key: string
      } & BorderSection)
    | ({
        _key: string
      } & HotspotSection)
    | ({
        _key: string
      } & HeaderSection)
    | ({
        _key: string
      } & TestimonialSection)
    | ({
        _key: string
      } & TeamSection)
    | ({
        _key: string
      } & RecipesSection)
    | ({
        _key: string
      } & VideoSection)
    | ({
        _key: string
      } & FeaturesListSection)
    | ({
        _key: string
      } & CtaSection)
    | ({
        _key: string
      } & NewsletterSection)
    | ({
        _key: string
      } & ImageCarouselSection)
    | ({
        _key: string
      } & BlogSection)
    | ({
        _key: string
      } & StepsSection)
    | ({
        _key: string
      } & TimelineSection)
    | ({
        _key: string
      } & LocationSection)
    | ({
        _key: string
      } & ContactSection)
    | ({
        _key: string
      } & ClientLoginSection)
  >
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  excerpt?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  featuredMedia?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  tileImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  categories?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'categories'
  }>
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  locale?: 'en-US' | 'en-GB' | 'fr-FR'
  title?: string
  slug?: Slug
  date?: string
  navColor?: SimplerColor
  navOverlay?: boolean
  pageBuilder?: Array<
    | ({
        _key: string
      } & EmbedSection)
    | ({
        _key: string
      } & TitleSection)
    | ({
        _key: string
      } & TextSection)
    | ({
        _key: string
      } & FeatureSection)
    | ({
        _key: string
      } & BorderSection)
    | ({
        _key: string
      } & HotspotSection)
    | ({
        _key: string
      } & HeaderSection)
    | ({
        _key: string
      } & TestimonialSection)
    | ({
        _key: string
      } & TeamSection)
    | ({
        _key: string
      } & RecipesSection)
    | ({
        _key: string
      } & VideoSection)
    | ({
        _key: string
      } & FeaturesListSection)
    | ({
        _key: string
      } & CtaSection)
    | ({
        _key: string
      } & NewsletterSection)
    | ({
        _key: string
      } & ImageCarouselSection)
    | ({
        _key: string
      } & BlogSection)
    | ({
        _key: string
      } & StepsSection)
    | ({
        _key: string
      } & TimelineSection)
    | ({
        _key: string
      } & LocationSection)
    | ({
        _key: string
      } & ContactSection)
    | ({
        _key: string
      } & ClientLoginSection)
  >
}

export type Recipes = {
  _id: string
  _type: 'recipes'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  locale?: 'en-US' | 'en-GB' | 'fr-FR'
  featuredMedia?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title?: string
  slug?: Slug
  modified?: string
  status?:
    | 'publish'
    | 'future'
    | 'draft'
    | 'pending'
    | 'private'
    | 'trash'
    | 'auto-draft'
    | 'inherit'
  duration?: Duration
  serves?: Serves
  date?: string
  ingredientsList?: IngredientsList
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  instructions?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          {
            _key: string
          } & TextColor
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  pageBuilder?: Array<
    | ({
        _key: string
      } & HeaderSection)
    | ({
        _key: string
      } & TestimonialSection)
    | ({
        _key: string
      } & TeamSection)
    | ({
        _key: string
      } & RecipesSection)
    | ({
        _key: string
      } & VideoSection)
    | ({
        _key: string
      } & FeaturesListSection)
    | ({
        _key: string
      } & CtaSection)
    | ({
        _key: string
      } & NewsletterSection)
    | ({
        _key: string
      } & ImageCarouselSection)
    | ({
        _key: string
      } & BlogSection)
    | ({
        _key: string
      } & StepsSection)
    | ({
        _key: string
      } & TimelineSection)
    | ({
        _key: string
      } & LocationSection)
    | ({
        _key: string
      } & ContactSection)
    | ({
        _key: string
      } & ClientLoginSection)
  >
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'recipesCategory'
  }
}

export type RecipesCategory = {
  _id: string
  _type: 'recipesCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  url?: string
  description?: string
  avatar?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Serves = {
  _type: 'serves'
  serves?: number
  note?: string
}

export type Duration = {
  _type: 'duration'
  hours?: number
  minutes?: number
}

export type FooterDetails = {
  _type: 'footerDetails'
  title?: string
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'body2' | 'h3' | 'h4' | 'h5'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | {
          reference?:
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'post'
              }
            | {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
          _type: 'internalLink'
          _key: string
        }
      | {
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  links?: Array<
    {
      _key: string
    } & LinkDefined
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type HighlightColor = {
  _type: 'highlightColor'
  label?: string
  value?: string
}

export type TextColor = {
  _type: 'textColor'
  label?: string
  value?: string
}

export type SimplerColor = {
  _type: 'simplerColor'
  label?: string
  value?: string
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SubItem
  | ServicesTile
  | ContactSection
  | BenifitsSection
  | LocationSection
  | ImageCarouselSection
  | TestimonialSection
  | HeaderSectionAccommodationSearch
  | Categories
  | Link
  | NavigationItem
  | Navigation
  | ColorChoice
  | Overlay
  | TextAlign
  | Icons
  | ClientLoginSection
  | LoginTile
  | TimeTile
  | TimelineSection
  | StepDivider
  | StepTile
  | StepsSection
  | TestimonialTile
  | BlogSection
  | ShowArchive
  | FeaturesTile
  | CtaSection
  | FeaturesListSection
  | VideoSection
  | VideoId
  | NewsletterSection
  | RecipesSection
  | TeamSection
  | HeaderSection
  | HotspotSection
  | BorderSection
  | TextSection
  | TitleSection
  | LinkDefined
  | EmbedSection
  | FeatureSection
  | Quote
  | HotspotItem
  | AccordionTile
  | ShowRecipesArchive
  | Cite
  | ExternalCite
  | TeamMember
  | TextColumns
  | SupportingAssets
  | Hotspots
  | ContainerWidth
  | VerticalSpace
  | IngredientItem
  | Ingredients
  | IngredientsList
  | ImageOptions
  | DesignSystemColor
  | NewsletterSetup
  | CompanyDetails
  | CompanyDetailType
  | Geopoint
  | SiteSettings
  | Post
  | Page
  | Recipes
  | RecipesCategory
  | SanityFileAsset
  | Author
  | Serves
  | Duration
  | FooterDetails
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | HighlightColor
  | TextColor
  | SimplerColor
  | Code
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MediaTag
  | Slug
export declare const internalGroqTypeReferenceTo: unique symbol
